"""empty message

Revision ID: 6e510e3f0c58
Revises: 8c68799f45c2
Create Date: 2021-04-21 12:53:09.422320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e510e3f0c58'
down_revision = '8c68799f45c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('watchlist', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'watchlist')
    # ### end Alembic commands ###
